version: 1
project:
  properties:
    ffmpeg: false
    temp-file-path: /Users/krasus1966/logs/temp/
    video-trans-path: /Users/krasus1966/logs/temp/
    extra-file-path: /Users/krasus1966/logs/temp/
    expire-time-login: 3600
    fail-lock-num: 5
    lock-login-expire: 300
server:
  port: 8888

spring:
  messages:
    basename: i18n.constants
    encoding: UTF-8
  profiles:
    active: dev
  application:
    name: system
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mariadb://localhost:11001/base_project?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 196610121
  mvc:
    throw-exception-if-no-handler-found: true
    path-match:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 2048MB
  web:
    resources:
      add-mappings: false
  redis:
    host: 127.0.0.1
    port: 11004
    password:
    database: 0
    lettuce:
      pool:
        max-idle: 20
        min-idle: 10
        max-active: 20
        max-wait: 60000ms
      shutdown-timeout: 120000ms
  data:
    mongodb:
      database: news
      username: admin
      password: '196610121'
      host: 127.0.0.1
      port: 27017
      authentication-database: news
      gridfs:
        bucket: news

mybatis-plus:
  type-aliases-package: top.krasus1966.*.domain.*
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: SCZT01
      logic-not-delete-value: SCZT02
  configuration:
    cache-enabled: true